import os

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded

from core.lifespan import lifespan
from core.limiter import limiter
from core.logger import setup_logging
from db.session import engine
from models import Base
from routes import auth, invitations, org, share, video
from routes import websocket as websocket_router

logger = setup_logging()
logger.info("Logger initialized.")

# Create tables defined by SQLAlchemy models. Idempotent; safe to call on
# every boot. Schema changes that require ALTER are handled by the
# lifespan shim until Alembic lands.
Base.metadata.create_all(bind=engine)

app = FastAPI(title="DocPilot API", version="0.1.0", lifespan=lifespan)

app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# Files generated by the worker live here. They are NOT served by a public
# static mount any more — every download flows through the signed-URL gated
# route in routes/video.py.
os.makedirs("temp_data", exist_ok=True)

app.include_router(auth.router, prefix="/api/v1/auth", tags=["auth"])
app.include_router(org.router, prefix="/api/v1/orgs", tags=["organizations"])
app.include_router(invitations.router, prefix="/api/v1/invitations", tags=["invitations"])
app.include_router(video.router, prefix="/api/v1/videos", tags=["videos"])
app.include_router(share.router, prefix="/api/v1", tags=["share"])
app.include_router(websocket_router.router, tags=["websockets"])

# Allowed origins: localhost for dev, plus anything in ALLOWED_ORIGINS env
# var (comma-separated). The frontend must match one of these for cookies
# / Authorization headers to work cross-origin.
_default_origins = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
]
_env_origins = [
    o.strip()
    for o in os.getenv("ALLOWED_ORIGINS", "").split(",")
    if o.strip()
]
origins = _default_origins + _env_origins

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type", "X-Org-Id"],
)


@app.get("/")
def read_root():
    return {"service": "docpilot-api", "status": "ok"}
