"""add_pdf_storage_path_and_frame_storage_paths

Revision ID: 05b6ac0a6519
Revises: cfd712450e51
Create Date: 2026-06-17 00:59:22.695090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05b6ac0a6519'
down_revision: Union[str, Sequence[str], None] = 'cfd712450e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('pdf_storage_path', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('frame_storage_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'frame_storage_paths')
    op.drop_column('videos', 'pdf_storage_path')
    # ### end Alembic commands ###
