"""add_video_shares

Revision ID: 15780a5b3413
Revises: 05b6ac0a6519
Create Date: 2026-06-17 01:32:00.361059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15780a5b3413'
down_revision: Union[str, Sequence[str], None] = '05b6ac0a6519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', name='uq_video_share_video')
    )
    op.create_index(op.f('ix_video_shares_token'), 'video_shares', ['token'], unique=True)
    op.create_index(op.f('ix_video_shares_video_id'), 'video_shares', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_shares_video_id'), table_name='video_shares')
    op.drop_index(op.f('ix_video_shares_token'), table_name='video_shares')
    op.drop_table('video_shares')
    # ### end Alembic commands ###
